name: CI/CD Pipeline
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Checkout du code
      - name: Checkout
        uses: actions/checkout@v3

      # Étape 2 : Configuration Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Aligné avec le JDK 17

      # Étape 3 : Compilation et tests
      - name: Build with Maven
        run: mvn compile

      - name: Run Tests
        run: mvn test

      # Étape 4 : Génération du JAR
      - name: Package JAR
        run: mvn package

      # Étape 5 : Déploiement (CD) - À AJOUTER
      - name: Deploy to Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "target/*.jar"
          target: "/home/user/app"

      - name: Start Application
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            pkill -f 'java -jar' || true
            nohup java -jar /home/user/app/*.jar > log.txt 2>&1 &
